window.cash = require('cash-dom');

// import './custom/js/custom'


// import './helper'
// import './chart'
// import './highlight'
// import './feather'
// import './tiny-slider'
// import './tippy'
// import './datepicker'
// import './tail-select'
// import './dropzone'
// import './validation'
// import './zoom'
// import './svg-loader'
// import './toast'
// import './tabulator'
//
//
// import './maps'
// import './chat'
// import './dropdown'
// import './modal'
// import './show-dropdown'
// import './show-modal'
// import './tab'
// import './accordion'
// import './search'
// import './copy-code'
// import './show-code'
// import './side-menu'
// import './mobile-menu'
// import './side-menu-tooltip'
